[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

# Add persistent volume for database storage
[[deploy.volumes]]
mountPath = "/app/data"
name = "reddit-monitor-data"